#!/bin/sh
#
#

set -e

case "$1" in
  configure)
    if [ -z "`getent group pdns`" ]; then
      addgroup --quiet --system pdns
    fi
    if [ -z "`getent passwd pdns`" ]; then
      echo -n "Creating user and group pdns..."
      adduser --quiet --system --home /var/spool/powerdns --shell /bin/false --ingroup pdns --disabled-password --disabled-login --gecos "PowerDNS" pdns
      echo "done"
    fi
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Remove old stuff (Coming from before 2.9.17) if Sarge is not supported anymore
# this can be replaced by dh_installinit in debian/rules.
if [ -f /etc/init.d/pdns_recursor ]; then
  if [ -x /usr/sbin/invoke-rc.d ]; then
    invoke-rc.d pdns_recursor stop || exit $?
  else
    /etc/init.d/pdns_recursor stop || exit $?
  fi
  update-rc.d -f pdns_recursor remove >/dev/null 2>&1
  rm -f /etc/init.d/pdns_recursor
fi

# Those using dependency based boot sequencing with sysv-rc and
# installing pdns-recursor version 3.1.7.1-2 or earlier would have wrong
# runlevel symlinks.  Recover from this.
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "3.1.7.1-2" \
	&& [ -f /etc/rc2.d/S[0-9][0-9]pdns-recursor ] && [ ! -f /etc/rc1.d/K[0-9][0-9]pdns-recursor ]
then
	update-rc.d -f pdns-recursor remove
fi


if [ -x "/etc/init.d/pdns-recursor" ]; then
  update-rc.d pdns-recursor defaults 19 85 >/dev/null
  if [ -x /usr/sbin/invoke-rc.d ]; then
    invoke-rc.d pdns-recursor start || exit $?
  else
    /etc/init.d/pdns-recursor start || exit $?
  fi
fi

#DEBHELPER#

exit 0

